### ISSUE TITLE
pyevtk in function writeVts

### ISSUE THREAD

**Issue by AlainPlattner** [AnkitBarik/planetMagFields#5]
Hi Ankit,

Thanks for creating and sharing this amazing software package.

To get pyevtk running on my computer, I needed to make the following changes on lines 105 and 106 in the file potextra.py
```import pyevtk```
```gridToVTK = pyevtk.hl.gridToVTK```

Just thought I'll let you know.

It's fun to load the output into Paraview and create beatiful images like this one:
![EarthField](https://user-images.githubusercontent.com/16839587/141965371-6f0a86ae-4910-45a0-9fa9-8abe4eb09f7c.png)

Best,
Alain

**Comment by AnkitBarik** [comment]
Hi Alain,

You've raised a good point. I prefer using the latest version of the evtk library from here: https://github.com/paulo-herrera/PyEVTK , which is imported as `evtk` ( and no longer `pyevtk`) but I have now added some extra lines to check for `pyevtk` since I think that is what `pip` installs by default. 

Fixed in 8270a97bba994f936fe52e1704701e14ce08cd13

Cheers,
Ankit
